ESR now listens to the environment defined events from EP
eiffel-community/etos-suite-runner pull request #25
Opened 2022-07-27 11:58 UTC by t-persson

### Applicable Issues

fixes: eiffel-community/etos#126

### Description of the Change

ESR will now listen to environment defined from environment provider, enabling us to easier implement sequential execution and partial check-in of environments and some preparations have been made to get there.
This change is tested locally against the environment provider version in a PR.

There are a few TODOs in the code. These will be fixed when we continue with this path. Some requirements in different parts of ETOS that need to be implemented to get there.

### Alternate Designs

We've discussed several alternatives offline. This one was selected as it was the easiest to understand and it utilizes the Eiffel protocol best.

### Benefits

Right now there are no real benefits to this, but in the future this will be vital for a few new features for ETOS as I hinted at in the description.

### Possible Drawbacks

A bit more volatile due to listening to events instead of APIs. Tried to remedy by waiting for the environment provider status in a thread and having a few robust HTTP waits.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2022-07-28 08:38 UTC, t-persson commented on src/etos_suite_runner/lib/runner.py
> +    def _environments(self, suite_name):
If there is a TERCC with two suites in it and one of them succeeds their checkout and the other fails, then there is a risk that the first suite has already started up and we will be checking in the environment before that first one has finished using it.
We must make sure that all suites that have started finish, before we attempt to check in the whole environment.

2022-07-28 08:56 UTC, t-persson commented on src/etos_suite_runner/lib/runner.py
> +            time.sleep(1)
This hammers the ER a bit too much. We should increase this sleep and also do one request per ESR instance instead of one request per suite.

2022-08-24 10:35 UTC, andjoe-axis commented on src/etos_suite_runner/__main__.py
Add param and type for ids in doc string

2022-08-24 10:47 UTC, andjoe-axis commented on src/etos_suite_runner/__main__.py
>          """Reserve workers for test."""
Add params, type,return , rtype

2022-08-25 08:00 UTC, andjoe-axis approved these changes

2022-08-25 11:40 UTC, fredjn requested changes

2022-08-25 12:12 UTC, t-persson commented on src/etos_suite_runner/__main__.py
> +        ids = []
I don't see this problem. We append IDs on the lines below like this `ids.append(suite["test_suite_started_id"])` should be clear enough that we are appending `test_suite_started_id`, no?

2022-08-25 12:15 UTC, t-persson commented on src/etos_suite_runner/__main__.py
>          """Trigger an activity and starts the actual test runner.
Done

2022-08-25 12:59 UTC, fredjn approved these changes

2022-08-25 13:03 UTC, andjoe-axis approved these changes

2022-08-25 13:04 UTC, merged