Run the environment provider locally
eiffel-community/etos-suite-runner pull request #51
Opened 2024-02-05 12:28 UTC by t-persson

### Applicable Issues

None

### Description of the Change

Note: This is expected to fail all tests due to changes in the environment provider not being ready.
Update to use the environment provider as a library instead of calling a microservice.

### Alternate Designs

There are a few things that are quite silly with this. We are creating JsonTas instances and ProviderRegistry instances etc.
We also call the environment provider in a thread and wait for Eiffel events.
It was decided that we should get this up and running as it is, before making changes to it. Since we want to make as few changes as possible per PR.

### Possible Drawbacks

We are changing something that has been the same in ETOS for a long time. There may be bugs. We have not made that many functional changes and instead make adaptations in the ESR to try to mitigate bug areas.

### Sign-off

Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Tobias Persson <tobias.persson@axis.com>

2024-02-07 10:19 UTC, fredjn requested changes

2024-02-07 10:43 UTC, t-persson commented on projects/etos_suite_runner/requirements.txt
> +# environment_provider@git+https://github.com/t-persson/etos-environment-provider@01ca7c4914fbdbaa4af79689cb768ab011fce410
Will be updated when the environment provider is ready

2024-02-15 21:40 UTC, fredjn commented on projects/etos_suite_runner/tests/library/fake_database.py
> +    """A fake database that follows the etcd client."""
What does follow the client mean? Match the available client commands/options?

2024-02-15 21:40 UTC, fredjn commented on projects/etos_suite_runner/tests/scenario/test_permutations.py
> +                    len(suite_ids), 2, "There shall only be a single test suite started."
The assert message here seems wrong.

2024-02-21 12:34 UTC, fredjn approved these changes

2024-02-22 08:13 UTC, merged