Add OpenTelemetry trace id to logstash entries
eiffel-community/etos-suite-runner pull request #62
Opened 2024-06-03 11:00 UTC by andmat900

### Applicable Issues

- https://github.com/eiffel-community/etos/issues/236

### Description of the Change

This change fixes OpenTelemetry context propagation among threads so that logstash entries receive the correct opentelemetry_trace_id value.

### Alternate Designs

### Possible Drawbacks

### Sign-off
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: Andrei Matveyeu, andrei.matveyeu@axis.com

2024-06-07 06:17 UTC, t-persson requested changes

2024-06-07 06:17 UTC, t-persson commented on projects/etos_suite_runner/src/etos_suite_runner/esr.py
> +        opentelemetry.context.attach(suite_context)
The token that is received from `attach` should be detached in a finally block.
This comment applies to all instances where context attachment is done

2024-06-07 12:49 UTC, t-persson requested changes

2024-06-10 12:14 UTC, fredjn approved these changes

2024-06-12 06:09 UTC, merged